package com.yimao.cloud.base.utils.yunSignUtil;

import com.yimao.cloud.base.utils.DateUtil;

import java.text.SimpleDateFormat;
import java.util.Date;

public class YunSignData {
    public YunSignData() {
    }

    public static String contractServiceData(String userName, String province, String city, String region, String address, String costMoney, String businessDeviceName, String businessDeviceMoney, String businessDeviceMonth, String homeDeviceName, String homeDeviceMoney, String homeDeviceMonth, String homeMoney, String businessMoney, String otherMoney, String otherName, String cycle, String firstMonth, String accountBank, String accountName, String account, String homePrice, String businessPrice, String payMoney, String openAccount, String additionalMonth, String firstServiceCycle, String peroidOfValidity, String year, String month, String day, String threeYear, String stopPaymentDays, String contractStopDays, String businessCompensate, String homeCompensate, String firstParty, String secondParty, String representative, String idCard, String firstPartyAddress, String secondPartyAddress, String firstPartyPhone, String secondPartyPhone) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy年MM月dd日");
        String data = "{\"loops1\":\"" + userName + "\",\"loops2\":\"" + province + "\",\"loops3\":\"" + city + "\",\"loops4\":\"" + region + "\",\"loops5\":\"" + address + "\",\"loops6\":\"" + costMoney + "\",\"loops7\":\"" + businessDeviceName + "\",\"loops8\":\"" + businessDeviceMoney + "\",\"loops9\":\"" + businessDeviceMonth + "\",\"loops10\":\"" + homeDeviceName + "\",\"loops11\":\"" + homeDeviceMoney + "\",\"loops12\":\"" + homeDeviceMonth + "\",\"loops13\":\"" + homeMoney + "\",\"loops14\":\"" + businessMoney + "\",\"loops15\":\"" + otherMoney + "\",\"loops16\":\"" + otherName + "\",\"loops17\":\"" + cycle + "\",\"loops18\":\"" + firstMonth + "\",\"loops19\":\"" + accountBank + "\",\"loops20\":\"" + accountName + "\",\"loops21\":\"" + account + "\",\"loops22\":\"" + homePrice + "\",\"loops23\":\"" + businessPrice + "\",\"loops24\":\"" + payMoney + "\",\"loops25\":\"" + openAccount + "\",\"loops26\":\"" + additionalMonth + "\",\"loops27\":\"" + firstServiceCycle + "\",\"loops28\":\"" + peroidOfValidity + "\",\"loops29\":\"" + year + "\",\"loops30\":\"" + month + "\",\"loops31\":\"" + day + "\",\"loops32\":\"" + threeYear + "\",\"loops33\":\"" + month + "\",\"loops34\":\"" + day + "\",\"loops35\":\"" + stopPaymentDays + "\",\"loops36\":\"" + contractStopDays + "\",\"loops37\":\"" + homeCompensate + "\",\"loops38\":\"" + businessCompensate + "\",\"loops39\":\"" + firstParty + "\",\"loops40\":\"" + secondParty + "\",\"loops41\":\"" + representative + "\",\"loops42\":\"" + idCard + "\",\"loops43\":\"" + firstPartyAddress + "\",\"loops44\":\"" + secondPartyAddress + "\",\"loops45\":\"" + firstPartyPhone + "\",\"loops46\":\"" + secondPartyPhone + "\",\"loops47\":\"" + sdf.format(new Date()) + "\",\"loops48\":\"" + sdf.format(new Date()) + "\"}";
        return data;
    }

    public static String contractData(String userName, String brand, String productModal, String snCode, String province, String city, String region, String address, String costType, String openAccount, String completeNotice, String homePrice, String businessPrice, String costChoose, String costMoney, String firstServiceCycle, String homeMoney, String businessMoney, String cycle, String accountBank, String accountName, String account, String peroidOfValidity, String year, String month, String day, String validityYear, String validityMonth, String validityDay, String stopPaymentDays, String homeCompensate, String firstParty, String secondParty, String representative, String idCard, String firstPartyAddress, String secondPartyAddress, String firstPartyPhone, String secondPartyPhone, String indemnity1, String indemnity2, String indemnity3, String indemnity4, String indemnity5, String indemnity6, String indemnity7, String indemnity8) {
        String now = DateUtil.getDateToString(new Date(), "yyyy年MM月dd日");
        String data = "{\"loops1\":\"" + userName.trim() + "\",\"loops2\":\"" + brand.trim() + "\",\"loops3\":\"" + productModal.trim() + "\",\"loops4\":\"" + snCode.trim() + "\",\"loops5\":\"\",\"loops6\":\"\",\"loops7\":\"\",\"loops8\":\"\",\"loops9\":\"\",\"loops10\":\"\",\"loops11\":\"" + province.trim() + "\",\"loops12\":\"" + city.trim() + "\",\"loops13\":\"" + region.trim() + "\",\"loops14\":\"" + address.trim() + "\",\"loops15\":\"" + costType.trim() + "\",\"loops16\":\"" + openAccount.trim() + "\",\"loops17\":\"" + completeNotice.trim() + "\",\"loops18\":\"" + homePrice.trim() + "\",\"loops19\":\"" + businessPrice.trim() + "\",\"loops20\":\"" + costChoose.trim() + "\",\"loops21\":\"" + costMoney.trim() + "\",\"loops22\":\"" + firstServiceCycle.trim() + "\",\"loops23\":\"" + homeMoney.trim() + "\",\"loops24\":\"" + businessMoney.trim() + "\",\"loops25\":\"" + cycle.trim() + "\",\"loops26\":\"" + accountBank.trim() + "\",\"loops27\":\"" + accountName.trim() + "\",\"loops28\":\"" + account.trim() + "\",\"loops29\":\"" + peroidOfValidity.trim() + "\",\"loops30\":\"" + year.trim() + "\",\"loops31\":\"" + month.trim() + "\",\"loops32\":\"" + day.trim() + "\",\"loops33\":\"" + validityYear.trim() + "\",\"loops34\":\"" + validityMonth.trim() + "\",\"loops35\":\"" + validityDay.trim() + "\",\"loops36\":\"" + stopPaymentDays.trim() + "\",\"loops37\":\"" + homeCompensate.trim() + "\",\"loops38\":\"" + firstParty.trim() + "\",\"loops39\":\"" + secondParty.trim() + "\",\"loops40\":\"" + representative.trim() + "\",\"loops41\":\"" + idCard.trim() + "\",\"loops42\":\"" + firstPartyAddress.trim() + "\",\"loops43\":\"" + secondPartyAddress.trim() + "\",\"loops44\":\"" + firstPartyPhone.trim() + "\",\"loops45\":\"" + secondPartyPhone.trim() + "\",\"loops46\":\"" + now.trim() + "\",\"loops47\":\"" + now.trim() + "\",\"loops48\":\"" + indemnity1.trim() + "\",\"loops49\":\"" + indemnity2.trim() + "\",\"loops50\":\"" + indemnity3.trim() + "\",\"loops51\":\"" + indemnity4.trim() + "\",\"loops52\":\"" + indemnity5.trim() + "\",\"loops53\":\"" + indemnity6.trim() + "\",\"loops54\":\"" + indemnity7.trim() + "\",\"loops55\":\"" + indemnity8.trim() + "\"}";
        return data;
    }

    public static String distributorContractData(int roleLevel, String orderId, String serverSiteName, String userName, String idNo, String moneyCommon, String moneyTry, String moneyCompany, String moneyCommonChinese, String moneyTryChines, String moneyCompanyChines, String configNumCommon, String configNumTry, int tryDay, String configNumCompany) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy年MM月dd日");
        String chooseRole = "9.1.2";
        if (roleLevel == 350) {
            chooseRole = "9.1.1";
        } else if (roleLevel == 950) {
            chooseRole = "9.1.3";
        }
        String data = "{\"loops1\":\"" + orderId + "\",\"loops2\":\"" + serverSiteName + "\",\"loops3\":\"" + userName + "\",\"loops4\":\" " + configNumTry + " \",\"loops5\":\"" + configNumCommon + "\",\"loops6\": \"  " + configNumCompany + "  \", \"loops7\": \"  " + configNumTry + "  \", \"loops8\": \" " + configNumCommon + " \",\"loops9\": \"  " + configNumCompany + "  \", \"loops10\": \" " + tryDay + " \",\"loops11\": \" " + chooseRole + " \",\"loops12\": \" " + moneyTryChines + "\",\"loops13\": \" " + moneyTry + " \",\"loops14\": \" " + moneyCommonChinese + " \",\"loops15\": \" " + moneyCommon + " \",\"loops16\": \" " + moneyCompanyChines + " \",\"loops17\": \" " + moneyCompany + " \",\"loops18\": \" " + sdf.format(new Date()) + "\",\"loops19\": \" " + idNo + "\",\"loops20\": \" " + sdf.format(new Date()) + "\",\"loops21\": \" " + sdf.format(new Date()) + "\"}";
        return data;
    }
}
